
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
function db(env){if(!env.DB)fail(503,'Shared planner is unavailable. Please try again.');return env.DB;}
async function identity(request,env){if(!env.user)fail(401,'Sign in to use the planner.');return env.user;}
function clean(data){const text=(k,max,required=false)=>{const value=typeof data[k]==='string'?data[k].trim():'';if(value.length>max||(required&&!value))fail(400,'Check the '+k+' field.');return value};const item={id:text('id',100,true),title:text('title',120,true),date:text('date',10,true),time:text('time',5,true),pillar:text('pillar',100,true),notes:text('notes',10000),videoLink:text('videoLink',2048),kind:data.kind==='request'?'request':'content',status:text('status',50)||'Draft'};if(!/^\d{4}-\d{2}-\d{2}$/.test(item.date)||!/^\d{2}:\d{2}$/.test(item.time))fail(400,'Choose a date and time.');item.platforms=Array.isArray(data.platforms)?data.platforms:typeof data.platform==='string'?[data.platform]:[];if(!item.platforms.length||item.platforms.length>8||item.platforms.some(x=>!['Instagram','Facebook','TikTok','YouTube','LinkedIn','Website','Other'].includes(x)))fail(400,'Choose valid platforms.');if(!['Draft','Pending review','Approved','Revision requested','Content requested'].includes(item.status))fail(400,'Choose a valid status.');if(item.videoLink){let url;try{url=new URL(item.videoLink)}catch{}if(!url||url.protocol!=='https:'||url.hostname!=='drive.google.com')fail(400,'Use a Google Drive HTTPS link.');}if(item.kind==='request'){item.requestedBy=text('requestedBy',100,true);item.contentTypes=Array.isArray(data.contentTypes)?data.contentTypes:[];if(!item.contentTypes.length||item.contentTypes.length>13||item.contentTypes.some(x=>typeof x!=='string'||x.length>100))fail(400,'Choose content types.');}return item;}
async function allItems(env){const store=db(env);const [rows,comments,decisions]=await Promise.all([store.prepare('SELECT payload,updated FROM content ORDER BY id').all(),store.prepare('SELECT * FROM feedback ORDER BY created_at').all(),store.prepare('SELECT * FROM reviews ORDER BY created_at').all()]);return rows.results.map(row=>{const item=JSON.parse(row.payload);return {...item,version:row.updated,comments:comments.results.filter(c=>c.content_id===item.id).map(c=>({id:c.id,text:c.text,author:c.author,createdAt:c.created_at})),reviews:decisions.results.filter(r=>r.content_id===item.id).map(r=>({author:r.author,decision:r.decision,createdAt:r.created_at}))}})}
async function body(request){const text=await request.text();if(text.length>250000)fail(413,'This request is too large.');try{return JSON.parse(text)}catch{fail(400,'Invalid request.')}}
export default {async fetch(request,env){try{const url=new URL(request.url);if(!url.pathname.startsWith('/api/')){const asset=ASSETS[url.pathname==='/'?'/index.html':url.pathname];if(!asset)return new Response('Not found',{status:404});return new Response(asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}const user=await identity(request,env);const store=db(env);if(url.pathname==='/api/planner'&&request.method==='GET')return json({user,items:await allItems(env)});
if(url.pathname==='/api/import'&&request.method==='POST'){if(user.role!=='manager')fail(403,'Only a manager can import items.');const data=await body(request);if(!Array.isArray(data.items)||data.items.length>500)fail(400,'Invalid import.');const count=await store.prepare('SELECT count(*) AS n FROM content').first();if(Number(count.n))return json({imported:false});const statements=[];for(const raw of data.items){const item=clean({...raw,requestedBy:raw.requestedBy||user.name,contentTypes:raw.contentTypes?.length?raw.contentTypes:['Other']});statements.push(store.prepare('INSERT OR IGNORE INTO content(id,payload,updated) VALUES(?,?,?)').bind(item.id,JSON.stringify(item),crypto.randomUUID()));for(const c of raw.comments||[]){if(typeof c.text!=='string'||!c.text.trim())continue;statements.push(store.prepare('INSERT OR IGNORE INTO feedback(id,content_id,user_id,author,text,created_at) VALUES(?,?,?,?,?,?)').bind(c.id||crypto.randomUUID(),item.id,user.id,c.author||user.name,c.text.slice(0,2000),c.createdAt||new Date().toISOString()));}}if(statements.length)await store.batch(statements);return json({imported:true});}
if(url.pathname==='/api/items'&&request.method==='POST'){const data=await body(request);const item=clean(data.item||{});if(user.role!=='manager'){if(item.kind!=='request')fail(403,'Only managers can create scheduled content.');item.status='Content requested';item.requestedBy=user.name;}await store.prepare('INSERT INTO content(id,payload,updated) VALUES(?,?,?)').bind(item.id,JSON.stringify(item),crypto.randomUUID()).run();return json({ok:true});}
const match=url.pathname.match(/^\/api\/items\/([^/]+)(?:\/(comments|review))?$/);if(!match)fail(404,'Not found.');const id=decodeURIComponent(match[1]);const existing=await store.prepare('SELECT payload,updated FROM content WHERE id=?').bind(id).first();if(!existing)fail(404,'This item has been removed.');const current=JSON.parse(existing.payload);
if(match[2]==='comments'&&request.method==='POST'){const data=await body(request);if(typeof data.text!=='string'||!data.text.trim()||data.text.length>2000)fail(400,'Write a comment of up to 2,000 characters.');await store.prepare('INSERT INTO feedback(id,content_id,user_id,author,text,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,user.id,user.name,data.text.trim(),new Date().toISOString()).run();return json({ok:true});}
if(match[2]==='review'&&request.method==='POST'){if(current.kind==='request')fail(400,'Only scheduled content can be reviewed.');const data=await body(request);if(!['Approved','Revision requested'].includes(data.decision))fail(400,'Choose approve or request revision.');current.status=data.decision;await store.batch([store.prepare("UPDATE content SET payload=json_set(payload,'$.status',?),updated=? WHERE id=?").bind(data.decision,crypto.randomUUID(),id),store.prepare('INSERT INTO reviews(id,content_id,user_id,author,decision,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),id,user.id,user.name,data.decision,new Date().toISOString())]);return json({ok:true});}
if(!match[2]&&request.method==='PUT'){if(user.role!=='manager')fail(403,'Visitors cannot edit content.');const data=await body(request);const item=clean({...data.item,id});const result=await store.prepare('UPDATE content SET payload=?,updated=? WHERE id=? AND updated=?').bind(JSON.stringify(item),crypto.randomUUID(),id,data.version||'').run();if(!result.meta.changes)fail(409,'This item changed. Close and reopen it before saving.');return json({ok:true});}
if(!match[2]&&request.method==='DELETE'){if(user.role!=='manager')fail(403,'Visitors cannot delete content.');await store.prepare('DELETE FROM content WHERE id=?').bind(id).run();return json({ok:true});}fail(405,'Action unavailable.');
}catch(error){if(!error.status)console.error('Planner API failure',error.message);return json({error:error.status?error.message:'The planner could not save or load. Please try again.'},error.status||503);}}};
