async function loadClerk(key){
const domain=atob(key.split('_')[2].replace(/-/g,'+').replace(/_/g,'/')).replace(/\$/,'');
if(!/^[a-z0-9.-]+$/i.test(domain))throw Error('Invalid Clerk publishable key.');
const uiScript=document.createElement('script');uiScript.src='https://'+domain+'/npm/@clerk/ui@1/dist/ui.browser.js';uiScript.crossOrigin='anonymous';
await new Promise((resolve,reject)=>{uiScript.onload=resolve;uiScript.onerror=()=>reject(Error('Clerk sign-in UI could not load.'));document.head.append(uiScript);});
const script=document.createElement('script');script.src='https://'+domain+'/npm/@clerk/clerk-js@6/dist/clerk.browser.js';script.setAttribute('data-clerk-publishable-key',key);script.crossOrigin='anonymous';
await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=()=>reject(Error('Clerk could not load.'));document.head.append(script);});await window.Clerk.load({ui:{ClerkUI:window.__internal_ClerkUICtor},localization:{signIn:{start:{title:'Sign in to Content Planner'}},signUp:{start:{title:'Create your Content Planner account'}}}});return window.Clerk;
}
async function start(){const status=document.getElementById('loadstate');try{const response=await fetch('/api/config');const config=await response.json();if(!response.ok)throw Error(config.error);const clerk=await loadClerk(config.publishableKey);if(!clerk.user){status.textContent='Sign in to your Content Planner.';const signInContainer=document.getElementById('signin');signInContainer.style.cssText='display:grid;place-items:center;width:100%;min-height:calc(100dvh - 190px);padding:24px 16px;box-sizing:border-box';clerk.mountSignIn(signInContainer,{forceRedirectUrl:window.location.origin,appearance:{elements:{rootBox:{margin:'0 auto',width:'fit-content',maxWidth:'100%'},cardBox:{margin:'0 auto',maxWidth:'100%'}}}});return;}clerk.mountUserButton(document.getElementById('account'));const rawFetch=window.fetch.bind(window);window.fetch=async(input,options={})=>{const url=new URL(typeof input==='string'?input:input.url,window.location.origin);if(url.origin===window.location.origin&&url.pathname.startsWith('/api/')){const token=await clerk.session?.getToken();const headers=new Headers(options.headers);if(token)headers.set('Authorization','Bearer '+token);return rawFetch(input,{...options,headers});}return rawFetch(input,options)};const uiScript=document.createElement('script');uiScript.src='https://'+domain+'/npm/@clerk/ui@1/dist/ui.browser.js';uiScript.crossOrigin='anonymous';
await new Promise((resolve,reject)=>{uiScript.onload=resolve;uiScript.onerror=()=>reject(Error('Clerk sign-in UI could not load.'));document.head.append(uiScript);});
const script=document.createElement('script');script.src='/app.js';document.body.append(script);clerk.addListener(({user})=>{if(!user)window.location.reload()});}catch(error){status.textContent=error.message||'Sign-in could not load. Refresh to try again.';}}start();


